name: Deploy

on:
  workflow_run:
    workflows: [Testing]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    environment: production
    env:
      INSTANT_APP_ID: ${{ vars.INSTANT_APP_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      # TODO: Use the artifact from the Testing workflow... seems quite complicated for now
      # https://stackoverflow.com/questions/67973057/github-actions-workflow-run-outputs
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ vars.DEPLOY_HOST }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          TARGET: ${{ vars.DEPLOY_TARGET }}
          SOURCE: './dist/'
          MODE: push
          VERBOSE: true
          PORT: ${{ vars.DEPLOY_PORT }}
          USER: ${{ vars.DEPLOY_USER }}
          ARGS: -avz --exclude-from=.gitignore --exclude=/.git/ --exclude=/.github/
